import { test, expect } from '@fixtures/base-test';

import { OwnerPage } from '@pages/owner-page';
import { createPet } from '@utils/pet-factory';

test.describe('Pet Management', () => {
  test('can add a pet to an existing owner and see it on owner details', async ({ page }, testInfo) => {
    const ownerPage = new OwnerPage(page);
    const pet = createPet({ type: 'cat' });

    await ownerPage.openFindOwners();
    await ownerPage.searchByLastName('Davis');
    await ownerPage.openOwnerDetailsByName('Betty Davis');

    await page.getByRole('link', { name: /Add New Pet/i }).click();

    // Form fields are generated by thymeleaf fragments: ids match field names
    await page.locator('input#name').fill(pet.name);
    await page.locator('input#birthDate').fill(pet.birthDate);
    await page.locator('select#type').selectOption({ label: pet.type });

    await page.screenshot({ path: testInfo.outputPath('pet-add-form-filled.png'), fullPage: true });

    await page.getByRole('button', { name: /Add Pet/i }).click();

    // Back on owner details
    await expect(page.getByRole('heading', { name: /Pets and Visits/i })).toBeVisible();
    await expect(page.getByText(pet.name, { exact: true })).toBeVisible();

    // Add a visit for the newly-created pet and verify it shows under visit history.
    const petRow = page.locator('tr').filter({
      has: page.locator('dd', { hasText: pet.name })
    });

    await petRow.getByRole('link', { name: /Add Visit/i }).first().click();

    await page.locator('input#date').fill('2024-01-01');
    await page.locator('input#description').fill('Annual checkup');
    await page.screenshot({ path: testInfo.outputPath('visit-add-form-filled.png'), fullPage: true });
    await page.getByRole('button', { name: /Add Visit/i }).click();

    await expect(page.getByRole('heading', { name: /Pets and Visits/i })).toBeVisible();
    await expect(petRow.getByRole('cell', { name: '2024-01-01', exact: true })).toBeVisible();
    await expect(petRow.getByRole('cell', { name: 'Annual checkup', exact: true })).toBeVisible();

    await page.screenshot({ path: testInfo.outputPath('pet-details-with-visit-history.png'), fullPage: true });
  });

  test('can delete a pet from an owner after confirming', async ({ page }, testInfo) => {
    const ownerPage = new OwnerPage(page);
    const pet = createPet({ type: 'dog' });

    // Arrange: add a uniquely-named pet to an existing owner.
    await ownerPage.openFindOwners();
    await ownerPage.searchByLastName('Davis');
    await ownerPage.openOwnerDetailsByName('Betty Davis');

    await page.getByRole('link', { name: /Add New Pet/i }).click();
    await page.locator('input#name').fill(pet.name);
    await page.locator('input#birthDate').fill(pet.birthDate);
    await page.locator('select#type').selectOption({ label: pet.type });
    await page.getByRole('button', { name: /Add Pet/i }).click();

    await expect(page.getByRole('heading', { name: /Pets and Visits/i })).toBeVisible();
    await expect(page.getByText(pet.name, { exact: true })).toBeVisible();

    // Act: open the confirmation page for that pet.
    const petRow = page.locator('tr').filter({
      has: page.locator('dd', { hasText: pet.name })
    });
    await petRow.getByRole('link', { name: /Delete Pet/i }).first().click();

    // Assert: the confirmation step is shown (no deletion yet). Capture the proof screenshot.
    await expect(page.getByRole('heading', { name: /Delete Pet/i })).toBeVisible();
    await expect(page.getByText(/cannot be undone/i)).toBeVisible();
    await page.screenshot({
      path: '../docs/specs/09-spec-delete-pet/09-proofs/img/confirm-delete-pet.png',
      fullPage: true
    });
    await page.screenshot({ path: testInfo.outputPath('confirm-delete-pet.png'), fullPage: true });

    // Confirm the deletion.
    await page.getByRole('button', { name: /Delete Pet/i }).click();

    // Assert: back on owner details and the pet is gone.
    await expect(page.getByRole('heading', { name: /Pets and Visits/i })).toBeVisible();
    await expect(page.getByText(pet.name, { exact: true })).toHaveCount(0);
    await page.screenshot({ path: testInfo.outputPath('owner-after-delete.png'), fullPage: true });
  });

  test('validates pet type selection and birth date format', async ({ page }) => {
    const ownerPage = new OwnerPage(page);

    await ownerPage.openFindOwners();
    await ownerPage.searchByLastName('Davis');
    await ownerPage.openOwnerDetailsByName('Betty Davis');

    await page.getByRole('link', { name: /Add New Pet/i }).click();

    // Validate required fields (observable via UI): leave name and birth date empty.
    await page.locator('select#type').selectOption({ index: 0 });
    await page.getByRole('button', { name: /Add Pet/i }).click();

    await expect(page.getByText(/is required/i)).toHaveCount(2);
  });
});
